const CONFIG = {
  name: "Codday996 Solutions",
  role: "Web Developer · Mobile Developer · DevSecOps",

  whatsapp: "6282312255030",
  waMessage: "Halo Codday996 Solutions, saya tertarik dengan jasa pembuatan sistem/aplikasi Anda. Boleh diskusi kebutuhan project saya?",
  email: "tarmizy.harsha@gmail.com",

  socials: [
    { icon: "gh", url: "https://github.com/tarmizy" },
    { icon: "ig", url: "" },
    { icon: "li", url: "" },
  ],

  projects: [
    {
      name: "MDNet",
      tag: "Manajemen Pelanggan WiFi",
      for: "Penyedia jasa internet / RT-RW Net",
      shortDesc: "Kelola pelanggan, tagihan, dan keuangan WiFi dari satu tempat — tanpa rekap manual.",
      problem: "Dulu catat pelanggan, tagihan, dan pemasukan masih terpisah — sering ada yang terlewat.",
      solution: "Sekarang semua jadi satu layar: siapa belum bayar, berapa pemasukan bulan ini, semua terlihat otomatis.",
      features: [
        "Daftar pelanggan & status tagihan",
        "Tagihan & pembayaran tercatat rapi",
        "Pemasukan & pengeluaran terlihat otomatis",
        "Pengingat jatuh tempo",
      ],
      stack: ["Admin Console", "Aplikasi Mobile", "Laporan Keuangan", "Multi-User"],
      url: "https://mdnet.pages.dev/",
      accent: "#3b82f6",
      shotDesktop: "/mdnet-desktop.png", shotMobile: "/mdnet-mobile.png",
    },
    {
      name: "Tahfidz Darul Rasyid",
      tag: "Aplikasi Pondok Pesantren",
      for: "Pondok pesantren & lembaga tahfidz",
      shortDesc: "Catat hafalan & absensi santri dari HP, laporan rapor langsung siap dibagikan ke orang tua.",
      problem: "Dulu hafalan dan absensi santri dicatat manual, orang tua tidak tahu perkembangan anaknya sampai akhir semester.",
      solution: "Sekarang ustadz cukup input dari HP, progres hafalan dan rapor PDF terbentuk otomatis untuk orang tua.",
      features: [
        "Ringkasan santri & pencapaian hafalan",
        "Catat setoran & absensi dari HP",
        "Ranking hafalan santri",
        "Rapor PDF untuk orang tua",
      ],
      stack: ["Sistem Pesantren", "Progres Hafalan", "Multi-User", "Laporan"],
      url: "https://tahfidz-darul-rasyid.pages.dev/",
      accent: "#06b6d4",
      shotDesktop: "/thafiz-desktop.png", shotMobile: "/tahfiz-mobile.png",
    },
    {
      name: "TPQ Digital",
      tag: "Manajemen TPQ & Santri",
      for: "Taman Pendidikan Al-Qur'an",
      shortDesc: "Ganti buku absen & prestasi manual jadi sistem yang rapi, laporan kehadiran terbentuk otomatis.",
      problem: "Dulu absensi dan progres bacaan santri tersebar di buku tulis, orang tua jarang mendapat laporan rutin.",
      solution: "Sekarang pengajar catat kehadiran & bacaan, laporan perkembangan tiap santri siap dibagikan ke orang tua.",
      features: [
        "Pendataan santri & pengajar",
        "Absensi & jadwal mengaji",
        "Progres bacaan / jilid",
        "Laporan kehadiran & perkembangan",
      ],
      stack: ["Sistem TPQ", "Absensi Digital", "Rapor Santri", "Responsive"],
      url: "https://tpq-digital.pages.dev/",
      accent: "#6366f1",
      shotDesktop: "/tpq-desktop.png", shotMobile: "/tpq-mobile.png",
    },
    {
      name: "HilingYuk",
      tag: "Perhotelan, Sewa Kendaraan & Wisata",
      for: "Hotel, penginapan, rental & travel",
      shortDesc: "Booking kamar, kendaraan, dan paket wisata dalam satu sistem — status kamar & transaksi terpantau jelas.",
      problem: "Dulu reservasi hotel, sewa kendaraan, dan paket wisata dicatat terpisah — sulit tahu kamar kosong atau tidak.",
      solution: "Sekarang semua booking tercatat di satu layar, status kamar dan transaksi tamu langsung terlihat.",
      features: [
        "Status kamar & reservasi langsung terlihat",
        "Booking hotel, kendaraan & paket wisata",
        "Room service & transaksi tamu",
        "Ringkasan okupansi & pendapatan",
      ],
      stack: ["Booking Hotel", "Sewa Kendaraan", "Paket Wisata", "Dashboard"],
      url: "https://hilingyuk.pages.dev/",
      accent: "#38bdf8",
      shotDesktop: "/hiling-desktop.png", shotMobile: "",
    },
    {
      name: "Makeup MUA",
      tag: "Website Profil & Booking",
      for: "Makeup artist, salon & jasa personal",
      shortDesc: "Landing page elegan untuk tampilkan galeri & layanan, klien bisa langsung booking lewat WhatsApp.",
      problem: "Dulu promosi hanya lewat media sosial, calon klien kesulitan melihat paket harga dan hasil kerja secara jelas.",
      solution: "Sekarang ada satu halaman: galeri, layanan, testimoni, dan tombol booking langsung — semua terlihat profesional.",
      features: [
        "Galeri & portfolio foto",
        "Daftar layanan & harga",
        "Testimoni klien",
        "Booking langsung via WhatsApp",
      ],
      stack: ["Landing Page", "Gallery", "Booking WA", "Responsive"],
      url: "https://evi-winda-makeup.pages.dev/",
      accent: "#f472b6",
      shotDesktop: "/Makeup-desktop.png", shotMobile: "",
    },
  ],

  pricing: [
    {
      name: "Profil Lembaga",
      desc: "Website profil lengkap untuk sekolah, pesantren, atau bisnis Anda.",
      price: "Rp 1.500.000",
      time: "5–10 hari kerja",
      features: [
        "Multi-halaman (profil, program, galeri, kontak)",
        "Tampilan rapi di HP & komputer",
        "Mudah ditemukan di Google",
        "Formulir kontak / tombol WhatsApp",
        "Bantuan setup domain & hosting",
      ],
    },
    {
      name: "Sistem Manajemen + Laporan",
      desc: "Aplikasi web untuk kelola data operasional harian — semua jadi otomatis.",
      price: "Rp 4.000.000",
      time: "3–6 minggu",
      featured: true,
      badge: "Paling Diminati",
      features: [
        "Dashboard ringkasan & modul data",
        "Laporan siap cetak & export",
        "Multi-user dengan hak akses",
        "Login aman & backup data",
        "Setup server, domain & langsung online",
        "Training untuk tim Anda",
        "Garansi perbaikan bug 30 hari",
      ],
    },
    {
      name: "Aplikasi Mobile / Custom",
      desc: "Aplikasi Android/iOS atau sistem besar dengan alur kerja khusus.",
      price: "Rp 8.000.000",
      time: "Timeline sesuai skala",
      features: [
        "Semua fitur Sistem Manajemen",
        "Aplikasi Android & iOS",
        "Integrasi payment / API",
        "Keamanan ekstra (DevSecOps)",
        "Deployment & maintenance",
      ],
    },
  ],

  addons: [
    { label: "Maintenance & support bulanan", price: "Rp 200rb / bln" },
    { label: "Domain + hosting (1 tahun)", price: "Rp 500rb" },
    { label: "Tambah modul / laporan baru", price: "Rp 500rb" },
    { label: "Training tambahan tim", price: "Rp 300rb / sesi" },
    { label: "Migrasi data dari Excel", price: "Rp 400rb" },
  ],

  trust: [
    { number: "3", label: "Sistem live & dipakai" },
    { number: "100%", label: "Nyaman di HP & desktop" },
    { number: "Laporan", label: "Otomatis tiap sistem" },
    { number: "< 24 jam", label: "Respon konsultasi" },
  ],

  process: [
    { step: "01", title: "Konsultasi", desc: "Ceritakan masalah Anda — gratis, tanpa komitmen." },
    { step: "02", title: "Rancangan & Harga", desc: "Fitur, tampilan, timeline, biaya — semua tertulis." },
    { step: "03", title: "Pengerjaan", desc: "Dibangun bertahap, Anda bisa pantau progres." },
    { step: "04", title: "Live + Training", desc: "Sistem online, tim dilatih, garansi maintenance." },
  ],
};

export default CONFIG;
